### ISSUE TITLE
Unable to process NCEP BUFR files - exits with StopIteration

### ISSUE THREAD

**Issue by Plantain** [ywangd/pybufrkit#30]
Something is throwing an exception deep inside pybufrkit while processing NCEP bufr files and I'm not able to figure out where it's coming from.

Data file:
http://static.skysight.io/ncep.bufr.gz

Versions:
% pybufrkit --version
pybufrkit: 0.2.20

% python --version
Python 3.10.6

Output:
% pybufrkit decode --continue-on-error  -m /tmp/ncep.bufr > out.txt
Traceback (most recent call last):
  File "/Users/plantain/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pybufrkit/decoder.py", line 422, in generate_bufr_message
    bufr_message = decoder.process(
  File "/Users/plantain/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pybufrkit/decoder.py", line 98, in process
    nbits_decoded += self.process_section(bufr_message, bit_reader, section)
  File "/Users/plantain/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pybufrkit/decoder.py", line 125, in process_section
    parameter.value = self.process_template_data(bufr_message, bit_reader)
  File "/Users/plantain/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pybufrkit/decoder.py", line 203, in process_template_data
    template_processing_func(state, bit_reader, template_to_process)
  File "/Users/plantain/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pybufrkit/templatecompiler.py", line 327, in process_compiled_template
    process_statements(coder, state, bit_operator, compiled_template.statements)
  File "/Users/plantain/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pybufrkit/templatecompiler.py", line 367, in process_statements
    process_statements(coder, state, bit_operator, statement.statements)
  File "/Users/plantain/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pybufrkit/templatecompiler.py", line 344, in process_statements
    getattr(state, statement.method_name)(*statement.args)
  File "/Users/plantain/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pybufrkit/coder.py", line 184, in add_bitmap_link
    idx_descriptor, _ = self.next_bitmapped_descriptor()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/plantain/.pyenv/versions/3.10.6/bin/pybufrkit", line 8, in <module>
    sys.exit(main())
  File "/Users/plantain/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pybufrkit/__init__.py", line 274, in main
    command_decode(ns)
  File "/Users/plantain/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pybufrkit/commands.py", line 62, in command_decode
    for bufr_message in generate_bufr_message(decoder, s,
RuntimeError: generator raised StopIteration

**Comment by ywangd** [comment]
This is now fixed in edc5c326e6fa4c4f79a78ca20758bad57a400c79

The reason is that the BUFR message defines a bit-map that has less entries than there are quality information. PyBufrKit builds relationships between descriptors and their quality information while decoding and it expects matched numbers between them. It throws error if such expectation is violated. Technically I think it can be argued that the BUFR message is not well composed because the extra quality information is useless. That said, since no other decoders attempt to automatically build such relationships, it is also reasonable for PyBufrKit to be more lenient. The fixed version will output something like the follows

```
...
  211 033007 PER CENT CONFIDENCE                                       ->     16 100
  212 033007 PER CENT CONFIDENCE                                       ->     17 100
  213 033007 PER CENT CONFIDENCE                                       ->     18 100
  214 033007 PER CENT CONFIDENCE                                                 None
...
```

Note the relationship is built for the first 3 quality information and they point (`-->`) to their associated descriptors denoted by the descriptor's index in the output, i.e. `16`, `17` and `18`. The last quality information is redunant and has no corresponding associated descriptor. The relationship building is now skipped in the latest version.

Thanks for reporting this issue.
